# author:hao.lu
# create_date: 9/24/2020 11:04 AM
# file : constant.py
# IDE: PyCharm

# ! -*- coding: utf-8 -*-

E_MAIL_REGULAR = r"[\w!#$%&'*+/=?^_`{|}~-]+(?:\.[\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\w](?:[\w-]*[\w])?\.)+[\w](?:[\w-]*[\w])?"
PHONE_REGULAR = r"^[0-9]*$"

DEFAULT_PASSWORD = "123456"

EN_EMAIL_FORMAT_VALIDATION_ERROR = "The email format is illegal."
JP_EMAIL_FORMAT_VALIDATION_ERROR = "メールのフォーマットは正当ではない."
CN_EMAIL_FORMAT_VALIDATION_ERROR = "邮箱格式不合法."
JSON_EMAIL_FORMAT_VALIDATION_ERROR = {
    "US": EN_EMAIL_FORMAT_VALIDATION_ERROR,
    "JP": JP_EMAIL_FORMAT_VALIDATION_ERROR,
    "CN": CN_EMAIL_FORMAT_VALIDATION_ERROR,
}

EN_EMAIL_REGISTERED_VALIDATION_ERROR = "The mailbox has been registered."
JP_EMAIL_REGISTERED_VALIDATION_ERROR = "メールボックスは既に登録されています."
CN_EMAIL_REGISTERED_VALIDATION_ERROR = "邮箱已经被注册."
JSON_EMAIL_REGISTERED_VALIDATION_ERROR = {
    "US": EN_EMAIL_REGISTERED_VALIDATION_ERROR,
    "JP": JP_EMAIL_REGISTERED_VALIDATION_ERROR,
    "CN": CN_EMAIL_REGISTERED_VALIDATION_ERROR,
}

EN_PHONE_FORMAT_VALIDATION_ERROR = "Cell phone Numbers are illegal."
JP_PHONE_FORMAT_VALIDATION_ERROR = "携帯電話の番号は合法ではない."
CN_PHONE_FORMAT_VALIDATION_ERROR = "手机号码不合法."
JSON_PHONE_FORMAT_VALIDATION_ERROR = {
    "US": EN_PHONE_FORMAT_VALIDATION_ERROR,
    "JP": JP_PHONE_FORMAT_VALIDATION_ERROR,
    "CN": CN_PHONE_FORMAT_VALIDATION_ERROR,
}

EN_PHONE_REGISTERED_VALIDATION_ERROR = "The mobile phone number has been registered."
JP_PHONE_REGISTERED_VALIDATION_ERROR = "携帯電話の番号は既に登録されている."
CN_PHONE_REGISTERED_VALIDATION_ERROR = "手机号码已经被注册."
JSON_PHONE_REGISTERED_VALIDATION_ERROR = {
    "US": EN_PHONE_REGISTERED_VALIDATION_ERROR,
    "JP": JP_PHONE_REGISTERED_VALIDATION_ERROR,
    "CN": CN_PHONE_REGISTERED_VALIDATION_ERROR,
}

EN_ACCOUNT_VALIDATION_ERROR = "The account already exists."
JP_ACCOUNT_VALIDATION_ERROR = "アカウントが存在する."
CN_ACCOUNT_VALIDATION_ERROR = "账号已存在."
JSON_ACCOUNT_VALIDATION_ERROR = {
    "US": EN_ACCOUNT_VALIDATION_ERROR,
    "JP": JP_ACCOUNT_VALIDATION_ERROR,
    "CN": CN_ACCOUNT_VALIDATION_ERROR,
}

EN_ROLE_VALIDATION_ERROR = "Role name already exists."
JP_ROLE_VALIDATION_ERROR = "キャラクター名が存在する."
CN_ROLE_VALIDATION_ERROR = "角色名称已存在."
JSON_ROLE_VALIDATION_ERROR = {
    "US": EN_ROLE_VALIDATION_ERROR,
    "JP": JP_ROLE_VALIDATION_ERROR,
    "CN": CN_ROLE_VALIDATION_ERROR,
}

EN_MENU_VALIDATION_ERROR = "The menu name already exists."
JP_MENU_VALIDATION_ERROR = "メニュー名が存在する."
CN_MENU_VALIDATION_ERROR = "菜单名称已存在."
JSON_MENU_VALIDATION_ERROR = {
    "US": EN_MENU_VALIDATION_ERROR,
    "JP": JP_MENU_VALIDATION_ERROR,
    "CN": CN_MENU_VALIDATION_ERROR,
}

EN_DEPT_VALIDATION_ERROR = "The department name already exists."
JP_DEPT_VALIDATION_ERROR = "部門名が存在する."
CN_DEPT_VALIDATION_ERROR = "部门名称已存在."
JSON_DEPT_VALIDATION_ERROR = {
    "US": EN_DEPT_VALIDATION_ERROR,
    "JP": JP_DEPT_VALIDATION_ERROR,
    "CN": CN_DEPT_VALIDATION_ERROR,
}

EN_POSITION_VALIDATION_ERROR = "The position already exists."
JP_POSITION_VALIDATION_ERROR = "役職名は既に存在する."
CN_POSITION_VALIDATION_ERROR = "职位名称已经存在."
JSON_POSITION_VALIDATION_ERROR = {
    "US": EN_POSITION_VALIDATION_ERROR,
    "JP": JP_POSITION_VALIDATION_ERROR,
    "CN": CN_POSITION_VALIDATION_ERROR,
}

EN_DICT_VALIDATION_ERROR = "The data dictionary name already exists."
JP_DICT_VALIDATION_ERROR = "データ辞書名はすでに存在する."
CN_DICT_VALIDATION_ERROR = "数据字典名称已经存在."
JSON_DICT_VALIDATION_ERROR = {
    "US": EN_DICT_VALIDATION_ERROR,
    "JP": JP_DICT_VALIDATION_ERROR,
    "CN": CN_DICT_VALIDATION_ERROR,
}

EN_DICT_TYPE_VALIDATION_ERROR = "The data dictionary type name already exists."
JP_DICT_TYPE_VALIDATION_ERROR = "データ辞書タイプ名はすでに存在する."
CN_DICT_TYPE_VALIDATION_ERROR = "数据字典类型名称已经存在."
JSON_DICT_TYPE_VALIDATION_ERROR = {
    "US": EN_DICT_TYPE_VALIDATION_ERROR,
    "JP": JP_DICT_TYPE_VALIDATION_ERROR,
    "CN": CN_DICT_TYPE_VALIDATION_ERROR,
}

EN_DICT_TYPE_CODE_VALIDATION_ERROR = "The data dictionary type code already exists."
JP_DICT_TYPE_CODE_VALIDATION_ERROR = "データ辞書型codeはすでに存在する."
CN_DICT_TYPE_CODE_VALIDATION_ERROR = "数据字典类型code已经存在."
JSON_DICT_TYPE_CODE_VALIDATION_ERROR = {
    "US": EN_DICT_TYPE_CODE_VALIDATION_ERROR,
    "JP": JP_DICT_TYPE_CODE_VALIDATION_ERROR,
    "CN": CN_DICT_TYPE_CODE_VALIDATION_ERROR,
}
